version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/o5z7i6s7

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t public.ecr.aws/o5z7i6s7/$IMAGE_REPO_NAME .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker images
      - docker push public.ecr.aws/o5z7i6s7/$IMAGE_REPO_NAME
